### ISSUE TITLE
Document user roles

### ISSUE THREAD

**Issue by ponceta** [QGEP/docs#103]
Missing

Ref : https://github.com/QGEP/QGEP/pull/394

Especially who does what.

https://github.com/QGEP/datamodel/compare/74c65a844fb005a599eeb8ee91db381bf282cd9d...1e02023ffde508caa2f3faf1a8ae703ec9664a05#diff-9351824c20dc5c44cddc0e57f0249adfR1

 - [x] qgep_viewer
 - [x] qgep_user
 - [x] qgep_manager
 - [x] qgep_sysadmin

In  https://github.com/QGEP/docs/tree/master/en/admin-guide

**Comment by ponceta** [comment]
@sjib this seems to be fixed or I don't find where you see the mention on the 12_roles.sql file.

**Comment by sjib** [comment]
@ponceta Yes this is corrected: https://qgep.github.io/docs/admin-guide/security/index.html#user-roles
