### ISSUE TITLE
The admin guide has dissapeared from the build

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/docs#12]
it seems the index files are missing. will try quickly to sort it out.

**Comment by tudorbarascu** [comment]
It seems there are multiple problems, I will make a pull request with a re-factored build.
Some of the errors:
``.. usage.rst:30: WARNING: image file not readable: admin-guide/pgadmin/images/Screenshot-from-2015-01-22-102152.png
usage.rst:31: WARNING: image file not readable: admin-guide/pgadmin/images/Screenshot-from-2015-01-22-102155.png
..usage.rst:32: WARNING: image file not readable: admin-guide/pgadmin/images/Screenshot-from-2015-01-22-102159.png
..usage.rst:34: WARNING: image file not readable: admin-guide/pgadmin/images/Screenshot-from-2015-01-22-102218.png
..usage.rst:39: WARNING: image file not readable: admin-guide/pgadmin/images/Screenshot-from-2015-01-22-102222.png
``

I searched the git history and the images with that name were never commited..

**Comment by m-kuhn** [comment]
Did #13 fix this?

If yes, I think you know that with a `fixes #13` in the commit message you can make it automatically close issues :wink:

**Comment by tudorbarascu** [comment]
:smile: Yes it did.
Thank you for believing I'm knowledgeable and although I knew about the feature, I had forgotten about it :wink: 
Thanks again for your tip!
