### ISSUE TITLE
Translating the projectfile

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/docs#129]
The actual projectfile has many untranslated values (e.g.  in the hydraulic - vw-tables > field alias). 
I think for the first version of the translation @m-kuhn did an automatic update with the values in the database.  Is that much work? (manual translation is boring...) 

There are also the fieldnames of vw_individual_surface missing in transifex.

**Comment by sjib** [comment]
@m-kuhn @urskaufmann I think this is solved - please re-open if not
