### ISSUE TITLE
Translation not visible

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/docs#166]
I have translated the chapters 2.8.3 - 2.8.5 (how to:  hydraulic modeling) into German same weeks ago, but in the Docu there is the english text. Something does not work!?

**Comment by urskaufmann** [comment]
German translation in the docu is now visible. Hope this works next time also...

**Comment by urskaufmann** [comment]
I have translated chap. 3.8.4 How to run symbology functions manually some days ago in transifex to german. It's still english in the docu... Does it no rebuild the docu every night?

**Comment by sjib** [comment]
> I have translated chap. 3.8.4 How to run symbology functions manually some days ago in transifex to german. It's still english in the docu... Does it no rebuild the docu every night?

@m-kuhn Can you check on this? And document how translation works. I was also thinking it does it every night.

**Comment by m-kuhn** [comment]
Should be fixed with https://github.com/QGEP/docs/commit/379442c55110b32c8eb816fe5b01ae30902ed2e3

What would you expect in terms of documentation?

**Comment by m-kuhn** [comment]
It looks like there is another problem with transifex now.
There was a recent update on the transifex tools, it's possible that more changes are needed (unrelated to this).

**Comment by sjib** [comment]
> What would you expect in terms of documentation?

Add the info how translations are integrated. eg. like "Translated sentences are integrated into the documentation automatically each night" or whatever it is.

https://github.com/QGEP/docs#process
and

Check your translated sentences the next day if they fit as expected in the language version of the documenation.
https://github.com/QGEP/docs#translation-process

**Comment by sjib** [comment]
How is transifex dealing with variations of languages? Does it make sense to agree to such a request?
`Project language requested: The French (Switzerland) language was requested for the[ QGEP Project File](https://www.transifex.com/qgep/qgep-project/languages/) project by XXX`

We have French right now. Same for German (Switzerland)

**Comment by sjib** [comment]
> There was a recent update on the transifex tools, it's possible that more changes are needed (unrelated to this).
@m-kuhn Can you check on them and fix them for qwat and qgep as part of the maintenance budget?

**Comment by urskaufmann** [comment]
Seems to work again
Thanks
