### ISSUE TITLE
Doc update process to transifex?

### ISSUE THREAD

**Issue by ponceta** [QGEP/docs#168]
@m-kuhn Can you tell what's the cycle (automatic, pseudo-automatic or manual) of doc releases to transifex?

I would like to extend a bit the Readme so that contributors know when their contributrions can be translated.

It seems that on https://github.com/qwat/docs an pseudo-automatic release of the doc to transifex (done every time a release is published) but with with no certainty.

**Comment by m-kuhn** [comment]
Each change on master is pushed to transifex automatically. As soon as a PR is merged (+5min) it can be translated.

**Comment by m-kuhn** [comment]
Not sure on qwat anything is happening still at all

![image](https://user-images.githubusercontent.com/588407/145054535-15029478-ad14-40dc-be5d-b789d2bfc442.png)

**Comment by m-kuhn** [comment]
last action about a year ago

**Comment by ponceta** [comment]
Initial question answered and doc update process running smoothly.
