### ISSUE TITLE
New QGIS functionnality Label Export -> How to use it

### ISSUE THREAD

**Issue by ponceta** [QGEP/docs#188]
Once QGIS doc section is released, we should document how to use this functionnality in the water and wastewater modules context.

https://github.com/qgis/QGIS-Documentation/issues/7260

**Comment by ponceta** [comment]
Since it is in the processing Toolbox it could be included in the wastewater module plugin.

**Comment by sjib** [comment]
Implementation with https://github.com/QGEP/qgepqwat2ili/pull/73 integrated in the INTERLIS Export Button

![case2](https://user-images.githubusercontent.com/1894106/186131850-1b28eb75-9c7d-495e-ba38-dd94af8d5133.png)

**Comment by sjib** [comment]
Documention is ready to be pushed: https://github.com/QGEP/docs/pull/192/files
