### ISSUE TITLE
using pgadmin chapter images missing

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/docs#19]
As seen from https://qgep.github.io/docs/admin-guide/pgadmin/usage.html the ** there are some links to images that don't exist.

There is a small fix in https://github.com/QGEP/docs/pull/18 but the images from the **3.1.2.2. Database dump** part are missing.
I checked and they never got pushed in the repo by @sjib and I cannot recover them from history.

@sjib Can you fix that part? Thanks!

**Comment by sjib** [comment]
Fix in #21 - hope it works

**Comment by sjib** [comment]
#21 went thru - @m-kuhn you can merge it

**Comment by m-kuhn** [comment]
@sjib there are merge conflicts because @tudorbarascu and you edited the same position in the files. Can you clear that up?

**Comment by sjib** [comment]
I don't know how to do that.

**Comment by tudorbarascu** [comment]
Closed in https://github.com/QGEP/docs/commit/e1a852c593a69f07f0e3991578ef39ce3bfd3341 thanks to Stefan
