### ISSUE TITLE
Transifex scripts are down, doc translations are broken too

### ISSUE THREAD

**Issue by ponceta** [QGEP/docs#204]
https://github.com/QGEP/docs/actions/runs/3986995003/jobs/6836228957#step:4:239

Script runs, builds, push, pull, ask but doesn't receive any translation in return.

**Comment by ponceta** [comment]
ping @why-not-try-calmer

**Comment by why-not-try-calmer** [comment]
On it

**Comment by m-kuhn** [comment]
@why-not-try-calmer you have received a couple of invitations to the respective transifex projects, that should give you a better base to work with. Let me know if you need more.

**Comment by ponceta** [comment]
If you need any rights and invitation, you can ping me as well for github or transifex or give me a call if you're stuck. @m-kuhn has my contact.

Organisations :

![image](https://user-images.githubusercontent.com/8614223/215034015-ac2ac752-66b4-4d7a-83c1-54eb6de919f5.png)

QWAT Documentation :
![image](https://user-images.githubusercontent.com/8614223/215034048-0edee701-ead8-4a5a-9abe-caf8f9bf6bd0.png)

QGEP Documentation :
![image](https://user-images.githubusercontent.com/8614223/215034132-dae3d311-90e9-495c-a34a-a2eae498ffba.png)

QGEP Project File :
![image](https://user-images.githubusercontent.com/8614223/215034167-a9739d9f-ecd0-41bc-baa1-5e341b3ab2aa.png)

**Comment by why-not-try-calmer** [comment]
Thank you very much, this will spare us a good deal of time

**Comment by ponceta** [comment]
@why-not-try-calmer I've invited you to the maintain permission, I hope this enable you to run the tests/actions for Pull requests

**Comment by ponceta** [comment]
build fails on release but not on pr :

https://github.com/QGEP/docs/actions/runs/4024439238/jobs/6916468971

**Comment by ponceta** [comment]
locally I get :

```
pulpoar@ubuntu:~/qgep_docs$ make transifex_pull
tx ERROR: ValueError: not enough values to unpack (expected 2, got 1)
make: *** [Makefile:97 : transifex_pull] Erreur 1
```

**Comment by ponceta** [comment]
```
pulpoar@ubuntu:~/qgep_docs$ make transifex_pull
# Getting info about resources

qgep-documentation.admin-guide - Get "/resources/o:qgep:p:qgep-documentation:r:admin-guide": unsupported protocol scheme ""
qgep-documentation.features-guide - Get "/resources/o:qgep:p:qgep-documentation:r:features-guide": unsupported protocol scheme ""
qgep-documentation.index - Get "/resources/o:qgep:p:qgep-documentation:r:index": unsupported protocol scheme ""
qgep-documentation.installation-guide - Get "/resources/o:qgep:p:qgep-documentation:r:installation-guide": unsupported protocol scheme ""
qgep-documentation.qgep_swmm - Get "/resources/o:qgep:p:qgep-documentation:r:qgep_swmm": unsupported protocol scheme ""
[##############################] (9 / 9)
Aborted
make: *** [Makefile:97 : transifex_pull] Erreur 1
pulpoar@ubuntu:~/qgep_docs$ 
```

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I've invited you to the maintain permission, I hope this enable you to run the tests/actions for Pull requests

Okay, thanks. I'll try to get everything done and working on Monday. Thanks for holding firm through all these trials-and-errors -- having access to the repos and transifex projects should definitely help me test things beforehand.

**Comment by ponceta** [comment]
I've managed to get to the filter error using the .\tx migrate command (as suggested here)

Maybe contact transifex team if you need any more hints (I've searched but did not find where we can find exac slugs for organisation, etc. , that is maybe the cause of our empty filters)

Thank you!

```
pulpoar@ubuntu:~/qgep_docs$ make transifex_pull
# Getting info about resources

qgep-documentation.admin-guide - file filter is empty
qgep-documentation.features-guide - file filter is empty
qgep-documentation.index - file filter is empty
qgep-documentation.installation-guide - file filter is empty
qgep-documentation.qgep_swmm - file filter is empty
[##############################] (9 / 9)
Aborted
make: *** [Makefile:97 : transifex_pull] Erreur 1
```

**Comment by why-not-try-calmer** [comment]
> I've managed to get to the filter error using the .\tx migrate command (as suggested [here](https://github.com/transifex/cli/issues/83))
> 
> Maybe contact transifex team if you need any more hints (I've searched but did not find where we can find exac slugs for organisation, etc. , that is maybe the cause of our empty filters)
> 
> Thank you!
> 
> ```
> pulpoar@ubuntu:~/qgep_docs$ make transifex_pull
> # Getting info about resources
> 
> qgep-documentation.admin-guide - file filter is empty
> qgep-documentation.features-guide - file filter is empty
> qgep-documentation.index - file filter is empty
> qgep-documentation.installation-guide - file filter is empty
> qgep-documentation.qgep_swmm - file filter is empty
> [##############################] (9 / 9)
> Aborted
> make: *** [Makefile:97 : transifex_pull] Erreur 1
> ```

I know how to fix this I think: the client expects a (mandatory) "file_filter" key under each entry in the tx config file (I initially thought it was optional). What I worry about is that assigning this key might require a different mapping from entries to resources (splitting resources into resources_languages). I'll see what can be done.

**Comment by why-not-try-calmer** [comment]
Thanks for the merge @ponceta, can this be considered solved?

**Comment by ponceta** [comment]
@why-not-try-calmer thank you for the fix!
