### ISSUE TITLE
Documentation of class organisation

### ISSUE THREAD

**Issue by sjib** [QGEP/docs#218]
Missing documentation

todo: This table is today at a strange place (it is not only related to wastewater structures) and has to be revised.
https://qgep.github.io/docs/user-guide/layerexplanations/layerexplanation.html#organisations-qgep-od-organisation

**Comment by urskaufmann** [comment]
if you search the table organisation in the old (and new) project, you find it in the group wastewater_structures (that is the strange place). For me it's ok, I don't know a better place today. Revised was then necessary for the subclasses.
I think we can forget this vw_organisation, the table is ok.

**Comment by sjib** [comment]
Solved with https://github.com/QGEP/docs/pull/219
