### ISSUE TITLE
Procedure to install a specific release is not documented

### ISSUE THREAD

**Issue by haubourg** [QGEP/docs#26]
Hi, 
the VM is not working on my machine, and faced issues (next tickets) with sample database or master plugin version. I didn't find a procedure documented to install a specific release from github repositories. 
Did I miss it?

**Comment by sjib** [comment]
@haubourg Is this still an issue? Else please close

**Comment by haubourg** [comment]
Of course not with the version policy now in place and the releases. Thanks for the garbage management task!
