### ISSUE TITLE
Sample VM does not work

### ISSUE THREAD

**Issue by haubourg** [QGEP/docs#27]
Hi, on my ubuntu 16.04 (lenovoX1 4 th gen), I can't run the virtual machine. debian startup shows and then I get a few errors and a dark screen. See attached log

[VBox.log.zip](https://github.com/QGEP/docs/files/558295/VBox.log.zip)

I hope that helps

**Comment by tudorbarascu** [comment]
I'll take a look. When I build it I tested it under virtualbox and kvm and it worked so you probably have a localized problem. I'll test again and get back at you.
Among other thoughts, I think the kernel inside the VM is a 4.6 or a 4.7, which translates that an older version of virtualbox may not support a kernel this new.

**Comment by tudorbarascu** [comment]
@haubourg I tested on 3 different OS/Virtualbox and on two in worked out of the box. On the thirds, I could replicate your issue. I did however a alt+ctrl+F1 to go to the first terminal and do a ``sudo apt-get update`` + ``sudo apt-get dist-upgrade`` and it worked afterwards.

While I was at it, I upgraded everything so now the vm has QGIS 2.18, pgadmin4 etc.
I retested under the 3 Virtualbox setups and it worked on each one.
So.. you can download again the recreated VM (compressed it's now around 2GB and uncompressed 8GB) and see if it works for you.

**Comment by haubourg** [comment]
Thanks Tudor! I will test that as at the end if the week. Cheers
Regus

**Comment by tudorbarascu** [comment]
@haubourg Think this can be closed, right?
