### ISSUE TITLE
QGIS can't open three tables from sample database 

### ISSUE THREAD

**Issue by haubourg** [QGEP/docs#29]
I'm using https://github.com/QGEP/data/raw/demodata/qgep_demodata.backup 
and qgis fails to open 3 tables :

![image](https://cloud.githubusercontent.com/assets/1629853/19806743/0cc6789e-9d1d-11e6-8ace-ec059cff0713.png)

**Comment by tudorbarascu** [comment]
For the **vw_network_segment** view it's on account of https://github.com/QGEP/docs/issues/28 so you can easily past that by doing a ``REFRESH MATERIALIZED VIEW qgep.vw_network_segment;``

I can replicate on the other two views without a solution though.
@m-kuhn any ideas?

**Comment by m-kuhn** [comment]
Moved to [main issue tracker](https://github.com/QGEP/QGEP/issues/241) (this one is for the docs).
