### ISSUE TITLE
Certificate error for VM

### ISSUE THREAD

**Issue by lbartoletti** [QGEP/docs#52]
@tudorbarascu 
FYI I can't download "simply" https://docs.qtibia.ro/qgis.vdi.xz
`docs.qtibia.ro uses an invalid security certificate. The certificate is only valid for the following names: gis.apavil.ro, www.gis.apavil.ro Error code: SSL_ERROR_BAD_CERT_DOMAIN
`

fetch http://docs.qtibia.ro/qgis.vdi.xz solve the problem

**Comment by tudorbarascu** [comment]
@lbartoletti The link was for http. Thanks for notifying me.
I've moved everything to https.
This can be closed.

**Comment by lbartoletti** [comment]
Thanks.
