### ISSUE TITLE
Datamodel init and upgrade

### ISSUE THREAD

**Issue by 3nids** [QGEP/docs#56]
role creation in setup is not documented
PUM upgrading and baseline not documented

**Comment by sjib** [comment]
Add to documention how to do it.

**Comment by sjib** [comment]
@varrieta can you share your experience in applying this?

**Comment by varrieta** [comment]
We are not currently using PUM (we're on windows) but we use the delta to file to keep the datamodel udpated.

**Comment by sjib** [comment]
* [DB customization](https://qgep.github.io/docs/installation-guide/database-initialization.html) and
* [Adding usr_ fields](https://qgep.github.io/docs/admin-guide/db-customization/index.html)
* [Database initialization](https://qgep.github.io/docs/installation-guide/database-initialization.html)
* [Geometry altitude 3D - Synchronisation](https://qgep.github.io/docs/user-guide/digitizing/digitizingchannels.html#geometry-synchronization) and [Implementation rules](https://github.com/QGEP/datamodel/pull/90)
* [Requirements](https://qgep.github.io/docs/installation-guide/database-initialization.html#generate-the-data-model)

**Comment by m-kuhn** [comment]
> We are not currently using PUM (we're on windows) but we use the delta file to keep the datamodel udpated.

Just to be precise: using pum is likely possible on windows. There is just no graphical frontend (GUI).

**Comment by varrieta** [comment]
I know, but I'm not really used to the command line ;P
