### ISSUE TITLE
Transifex for wincan2qgep

### ISSUE THREAD

**Issue by ponceta** [QGEP/docs#98]
I can't access to wincan2qgep translation on transifex?

![image](https://user-images.githubusercontent.com/8614223/65434410-0c1b9f00-de1f-11e9-872a-7c82c3ea09a3.png)

**Comment by ponceta** [comment]
Ping @3nids

**Comment by ponceta** [comment]
Probablement lié à travis : https://travis-ci.org/QGEP/docs/jobs/588482431#L493

**Comment by 3nids** [comment]
fixed, see https://www.transifex.com/qgep/qgep-documentation/wincan2qgep/
